Update pages.yml

diff --git a/.github/workflows/pages.yml b/.github/workflows/pages.yml
--- a/.github/workflows/pages.yml
+++ b/.github/workflows/pages.yml
@@ -18,5 +18,12 @@ jobs:
       - name: Run
         run: screen -dmS rukkit java -Dfile.encoding=UTF-8 -Djava.library.path=. -cp Rukkit-0.9.4-dev-240811.jar:libs/* cn.rukkit.RukkitLauncher;
           sleep 5;
-          screen -S rukkit -X stuff "say Server started\n"
+          screen -S rukkit -X stuff "say Server started\n";
+         
+          if screen -list | grep -q "rukkit"; then
+            echo "✅ Server is running"
+          else
+            echo "❌ Server failed to start"
+            exit 1
+          fi
       
